### ISSUE TITLE
Errors faced while running TempOS on Fedora regarding GDTR and IDTR

### ISSUE THREAD

**Issue by caped-crusader16** [rene/tempos#7]
I was trying to **fix GRUB2** as mentioned in the code. (To Do : Fix GRUB2) and so I tried running TempOS on Fedora as Grub2 commands are available there. While running make command, I got this issue

![issue1](https://user-images.githubusercontent.com/52067786/97974142-2deea000-1ded-11eb-97bc-46eb61eea0a4.png)

Now actually I tried understanding and debugging the kernel/arch/x86/idt.c, kernel/arch/include/x86/idt.h, kernel/arch/x86/boot/karch.c files as mentioned in the error, but couldn't find a way out. Until I understood, karch.c sets-up the IDT which is defined in idt.c and the structure idtr used in idt.c is defined in idt.h. So i didn't find any duplicate definition. So could you please have a look on this? **Actually my main doubt was that there were no errors faced regarding architecture while running on Ubuntu then why it gives such error in Fedora (Bcoz if it were a syntactic error as mentioned in the image, shouldn't it occur on Ubuntu as well)**. Also I would like to add that I am using Fedora in Oracle VM VirtualBox.

**Comment by nzeroxed** [comment]
You need to add **-fcommon** in CFLAGS in **kernel/arch/x86/build/Makefile** 😅 
This works for me on Debian 11 distrib

![image](https://user-images.githubusercontent.com/12203917/132536459-92c05377-f954-40cf-be59-c1421e812c6a.png)

**Comment by rene** [comment]
This issue is now fixed at master.
